### ISSUE TITLE
Invalid id: "unknown"

### ISSUE THREAD

**Issue by bsideup** [aws-quickstart/quickstart-confluent-kafka#50] opened 2017-10-18 12:59 UTC
Hi!

My cluster failed to start. When I SSH to the instance, I see:
```
An error occurred (InvalidInstanceID.Malformed) when calling the DescribeInstances operation: Invalid id: "unknown"
No AWS Cloudformation Stack specified; aborting script
post-cp-info: Executing on ip-10-0-0-195 (broker 1)
   for cluster my-clustr-name-here
        broker_index != 0; nothing to do
```

in the logs.

**Comment by cyan-confluent** [comment] 2017-11-06 19:34
I believe this is a duplicate of Issue Number #49. The PR #53 should resolve this. Wait for it to make it to master.

**Comment by santiagocardenas** [comment] 2017-11-13 21:59
Closing due to inactivity.

**Closed by santiagocardenas** 2017-11-13 21:59 UTC
