### ISSUE TITLE
Confluent Kafka Quickstart Deployment - changes to server.properties

### ISSUE THREAD

**Issue by bobby259** [aws-quickstart/quickstart-confluent-kafka#31] opened 2017-07-06 20:29 UTC
We deployed quickstart recently and I want my team to be able to interact with this cluster (on EC2 instances) from our local machines. 

What is the best solution for this?

**Comment by dbtucker** [comment] 2017-07-06 20:59
The solution I use is to update my local /etc/hosts file with the proper addressing for the quickstart nodes.   I do this so often that I've even written a helper script 

<pre>
my_cluster=${1:-awsqs}
shift

aws ec2 describe-instances --output text $@ \
  --filters 'Name=instance-state-name,Values=running' \
  --query 'Reservations[].Instances[].[PublicIpAddress,PrivateDnsName,Tags[?Key == `Name`] | [0].Value ]' | \
  grep -e "${my_cluster}-"  | sort -k 3 | \
while read pub_ip priv_fqdn node_name
do
    printf "%-14s %-16s %s %s\n"  $pub_ip ${priv_fqdn%%.*} $priv_fqdn $node_name
done
</pre>

This generates output of the form

<pre>
52.38.8.117 ip-10-20-12-7    ip-10-20-12-7.us-west-2.compute.internal awsqs-broker-0
54.200.110.242 ip-10-20-12-8    ip-10-20-12-8.us-west-2.compute.internal awsqs-worker-0
54.218.81.187 ip-10-20-12-9    ip-10-20-12-9.us-west-2.compute.internal awsqs-zookeeper-0
</pre>

which can be added directly to your local /etc/hosts to enable the proper execution of Kafka commands from that machine (assuming your quickstart deployment had the proper CIDR to allow traffic in on the broker and zookeeper ports).

<pre>
kafka-topics --zookeeper awsqs-zookeeper-0:2181 --list
kafka-console-consumer --new-consumer --bootstrap-server awsqs-broker-0:9092 --topic foo 
</pre>

The alternative of updating the server.properties files to specify the AWS public IP of the hosts as the advertised listener for the broker has the disadvantage of routing all traffic (even between brokers) across that public interface.     

The latest versions of Kafka support cleaner separation of intra-broker and client-broker network traffic, but we have not yet integrated that configuration option with the quickstart.

**Comment by bobby259** [comment] 2017-07-06 21:37
Hello dbtucker,

Thanks a ton for the help. I am completely new to this so please bear with me.. In the below line:

`52.38.8.117 ip-10-20-12-7    ip-10-20-12-7.us-west-2.compute.internal awsqs-broker-0`
`Public IP         Priv IP                   Priv Fully Qualified Name                          Node Name`

How to know my node name?

**Comment by dbtucker** [comment] 2017-07-06 22:17
It is a bit confusing.   "Node Name" in my helper script is simply the extraction of the metadata tag "Name" for each instance.   Under the covers, the Quickstart Template adds a "Name" tag to each instance to reflect its role in the cluster.  So a cluster with 3 brokers, 1 zookeeper, and 2 workers will have the following names assigned to the 6 nodes:
     <cluster_name>-broker-0
     <cluster_name>-broker-1
     <cluster_name>-broker-2
     <cluster_name>-zookeeper-0
     <cluster_name>-worker-0
     <cluster_name>-worker-1

I find those names helpful when I'm looking at the AWS EC2 portal and want to track which running instances are associated with my cluster.

The query syntax for the aws command-line tool requires that you retrieve each metadata tag separately, by name ... thus the "Tags[?Key == `Name`]" expression above.

**Comment by bobby259** [comment] 2017-07-06 22:40
So you mean, it is just a matter of reference and I can name use text in place of "Node Name". Am I correct?

**Comment by dbtucker** [comment] 2017-07-06 22:45
Correct.  The first three items in the host entry (Public_IP,  Private_Hostname, Private_FQDN), should be left alone ... as those effectively map the internal hostnames of your cluster nodes to the public IP that will be used by Kafka clients OUTSIDE the VPC's internal network.

That last item (Node_name) is just a helper alias.   You could have that be anything you want.   The only thing you want to avoid is using the same text string for multiple IP addresses, as many client applications will only use the first instance they find.

**Comment by bobby259** [comment] 2017-07-06 23:12
I have got my /etc/hosts entries in below format:
`54.157.9.212 ip-172-30-0-53 ip-172-30-0-53.ec2.internal brokernode1`

It doesn't seem to be working. Did I miss something other than updating the /etc/hosts file?

**Comment by bobby259** [comment] 2017-07-06 23:17
I am seeing this error when I am trying to list the topics:

```
$ kafka-topics --zookeeper zookeepernode1:2181 --list
WARN Client session timed out, have not heard from server in 30002ms for sessionid 0x0 (org.apache.zookeeper.ClientCnxn)
Exception in thread "main" org.I0Itec.zkclient.exception.ZkTimeoutException: Unable to connect to zookeeper server 'ip-172-30-0-229:2181' with timeout of 30000 ms
        at org.I0Itec.zkclient.ZkClient.connect(ZkClient.java:1233)
        at org.I0Itec.zkclient.ZkClient.<init>(ZkClient.java:157)
        at org.I0Itec.zkclient.ZkClient.<init>(ZkClient.java:131)
        at kafka.utils.ZkUtils$.createZkClientAndConnection(ZkUtils.scala:106)
        at kafka.utils.ZkUtils$.apply(ZkUtils.scala:88)
        at kafka.admin.TopicCommand$.main(TopicCommand.scala:53)
        at kafka.admin.TopicCommand.main(TopicCommand.scala)

```

**Comment by dbtucker** [comment] 2017-07-06 23:23
That looks like the proper ports have not been opened into your VPC for your client address.

When you deployed the Quickstart, you specified some CIDR settings to enable SSH traffic and Kafka traffic into the cluster (SSHAccessCIDR and RemoteAccessCIDR).   Is your client system covered by that CIDR ?   

The network configuration for AWS services is definitely complex.   It's worth connecting with your internal IT team or someone on the AWS side who can work with you on-site to troubleshoot this.

**Comment by bobby259** [comment] 2017-07-06 23:28
Yes I made sure my client IP was covered in SSHAccessCIDR and RemoteAccessCIDR while deploying the Quickstart.
Anyway, thank you for the help David. Appreciate it.

**Comment by dbtucker** [comment] 2017-07-06 23:35
Good luck, Bobby.   I know how tough it can be to resolve AWS network connectivity issues.

**Comment by bobby259** [comment] 2017-07-07 14:00
Hey David,
Everything works well when I remove entries in /etc/hosts file except that I am unable to make requests from local.
Things stop working when I update /etc/hosts file. Do you think I am missing something? Is there a workaround for this?

**Comment by dbtucker** [comment] 2017-07-07 15:25
Is your client system within the same VPC as the cluster, or outside ?   My assumption has been that you are working from your laptop, updating that system's /etc/hosts file so as to enable connection to the cluster deployed in an AWS VPC.   

If your client system is inside in the same VPC as the Confluent cluster, there is no need to add any entries to /etc/hosts ... you'll just resolve the hostnames as the internal ip-W-X-Y-Z names.   You could add more logical entries, but you'd want to use the private IP address (eg 172.30.0.53 in your above example).   So you could have an entry like
     172.30.0.53   ip-172-30-0-53    brokernode1

so you could use "--bootstrap-server brokernode1:9092" in your Kafka commands.   You definitely need to include the "official" hostnames in those entries; failure to do so can cause subtle problems with lots of applications.

**Comment by bobby259** [comment] 2017-07-07 16:07
My client is outside the VPC. I am working from my laptop but updating /etc/hosts file on each of the kafka ec2 instances with the entries we discussed earlier. My aim is to be able to use IntelliJ on my local windows laptop and run producer and consumer programs from my local making requests to Confluent Kafka Cluster (Quickstart) on AWS. Which means I want my laptop to be the client machine.

**Comment by dbtucker** [comment] 2017-07-07 16:21
Ah ... that's the problem.   There's no need to update the /etc/hosts file on the ec2 instances.   They have internal DNS that does the right thing, and the template has set up the Confluent software to use those internal addresses.

My recommendation on changing /etc/hosts was intended for your client machine (your laptop).   Having that system resolve "ip-172-30-0-53" to the public-facing IP address (54.157.9.212) should enable the kafka tools on your laptop to function properly.

Hope that makes more sense.

**Comment by bobby259** [comment] 2017-07-07 17:59
I have now updated my local hosts file but still facing this issue. I am able to list topics, create topics from my local but not produce data to the topic. I think it is still the same situation. Are we missing something?

**Comment by dbtucker** [comment] 2017-07-07 18:10
Do any of the other ports work ?   Can you use your browser to connect to "worker-0:9021" ... which should be the Control Center UI ?   curl should be able to get something back from port 8082 and 8083 on each worker node as well.

**Comment by bobby259** [comment] 2017-07-07 19:18
Yes, worker-0:9021 on browser works. But, kafka is still inaccessible. Cannot post messages to topic yet. I tried curls and they fail too..

**Comment by bobby259** [comment] 2017-07-07 20:37
Hey David,
I have got this working. Thank you so much for your support. It was some networking issue which I troubleshooted with help of my colleague. Appreciate your patience on this.

**Comment by dbtucker** [comment] 2017-07-07 20:38
Glad to hear it.   If there was anything that should have been done differently with the Security Groups or VPC in the template, please do log a specific issue.

Happy Kafka'ing !

**Closed** 2017-07-08 00:02 UTC

**Comment by dmacthedestroyer** [comment] 2018-10-31 18:19
so... is the proposed solution to this having everyone update their `hosts` file, or is there something that should/can be done in the cloudformation template to have the `advertised.listeners` be set?

**Comment by cyan-confluent** [comment] 2018-11-01 20:08
I think we can add some intelligent logic to the cloud formations template.

Add in a listener mapping, name the local listeners INTERNAL.
Basically keep the internal listeners the same, and specify inter.broker.listener.name=INTERNAL.
Add in external listener on a separate port, labeled it EXTERNAL.

Document that users outside of the AWS VPC use the EXTERNAL ports. This might cause some confusion if people don't pay attention to the documents and use the correct ports, but it would provide convenience to those that need this duality.

**Comment by dmacthedestroyer** [comment] 2018-11-01 20:35
I feel like connecting to the cluster from a dev's local build environment (or some other external environment) is a fairly common use case, but then again I'm new to using Kafka. Hence the quickstart :)
