### ISSUE TITLE
ClusterInfoCondition fails

### ISSUE THREAD

**Issue by bsideup** [aws-quickstart/quickstart-confluent-kafka#49] opened 2017-10-18 12:19 UTC
Hi!

I'm trying to start the cluster but it fails with:
```
WaitCondition timed out. Received 0 conditions when expecting 1
```

Parameters:
```

Key | Value
-- | --
AssignPublicIP | true
BrokerNodeInstanceType | m4.large
BrokerNodeStorage | 512
BrokerNodeStorageType | st1
ClusterName | mycluster
ConfluentEdition | Confluent Open Source
ConfluentVersion | 3.3.0
KeyPairName | some-keypair
LinuxOSAMI | Amazon-Linux-HVM
NumBrokers | 1
NumWorkers | 1
NumZookeepers | 0
QSS3BucketName | quickstart-reference
QSS3KeyPrefix | confluent/kafka/latest/
RemoteAccessCIDR | 10.0.0.0/16
SSHAccessCIDR | 10.0.0.0/16
SubnetID | subnet-123,subnet-456,subnet-789
VPCID | vpc-123123
WorkerNodeInstanceType | m3.large
```

**Comment by parveenkhera** [comment] 2017-10-26 06:14
Facing same issue while building Stack from own hosted repository in S3:

Parameters:
```
AssignPublicIP	false
BootDiskSize	16
BrokerNodeInstanceType	m4.xlarge
BrokerNodeSpotPrice	0.00
BrokerNodeStorage	512
BrokerNodeStorageType	st1
ClusterName	Confluent-Kafka
ConfluentEdition	Confluent Open Source
ConfluentVersion	3.3.0
ConnectorURLs	
KeyPairName	xxxxxxxxxxxx
LinuxOSAMI	CentOS-7-HVM
NumBrokers	3
NumWorkers	2
NumZookeepers	3
QSS3BucketName	xxxxxxxxxxxx
QSS3KeyPrefix	CFTs/quickstart-confluent-kafka-master/
RemoteAccessCIDR	172.16.0.0/16
SSHAccessCIDR	172.16.0.0/16
SubnetID	 subnet-xxxxxx,subnet-xxxxxx,subnet-xxxxxxx
VPCID	vpc-xxxxxx
WorkerNodeInstanceType	m4.xlarge
WorkerNodeSpotPrice	0.00
WorkerNodeStorage	16
ZookeeperNodeInstanceType	m4.large
ZookeeperNodeSpotPrice	0.00
ZookeeperNodeStorage	16

```
While using three subnets all the nodes have same name i.e. two broker nodes are assigned with  same name Confluent-Kafka-broker-0, three zookeeper nodes Confluent-Kafka-zookeeper-0 and two worker nodes Confluent-Kafka-worker-0. 

Expected is nodes should have names like Confluent-Kafka-broker-0, Confluent-Kafka-broker-1

While using single subnet node names came up fine but in both cases deployment failed with following error:


```
11:15:36 UTC+0550 | CREATE_FAILED | AWS::CloudFormation::Stack | Confluent-Kafka-Cluster | The following resource(s) failed to create: [ClusterInfoCondition].
-- | -- | -- | -- | --
  | Physical ID:arn:aws:cloudformation:us-west-2:xxxxxxxxxxxxx:stack/Confluent-Kafka-Cluster/beffe7c0-ba0e-11e7-ad17-50d5ca2e7cd2
  | Client Request Token:Console-CreateStack-5112b3df-2da2-4232-9746-656fe4f10564
  | 11:15:35 UTC+0550 | CREATE_FAILED | AWS::CloudFormation::WaitCondition | ClusterInfoCondition | WaitCondition timed out. Received 0 conditions when expecting 1
  | Physical ID:arn:aws:cloudformation:us-west-2:xxxxxxxxxxxxxxx:stack/Confluent-Kafka-Cluster/beffe7c0-ba0e-11e7-ad17-50d5ca2e7cd2/ClusterInfoHandle
  | Client Request Token:Console-CreateStack-5112b3df-2da2-4232-9746-656fe4f10564

```

**Comment by parveenkhera** [comment] 2017-10-26 07:44
Built successfully by checking out code from d5b6ad7dc40e296ee7f4c58131bb186ad4937afa hash. Post this commit there are 5 more commits, one for update submodules and 4 for update of AMIs.

This issue doesn't seems caused by update submodules commit "ce15be3152f08e6258066c7cbb40e6b9f768f01b" , this has to do something with Update of AMI but not sure.

**Comment by dbtucker** [comment] 2017-11-01 22:30
This appears to be an issue with some regions/VPC's where "hostname" internally returns the FQDN.   Will fix post-cp-info.sh to use "hostname -s", which should fix the issue.

**Comment by cyan-confluent** [comment] 2017-11-06 17:43
Hi Guys:

    I think this pull request resolves the issues. I tested with all three distros.

https://github.com/aws-quickstart/quickstart-confluent-kafka/pull/53

**Comment by joncourt** [comment] 2017-11-06 23:38
thanks cyan-confluent.

no good for me though... i believe my problem is that it's a private vpc and CF can't access the instances in there. Normally i'd do this through a bastion server or similar, i'm not sure about CF though.

does my hypothesis sound correct? if so i'll fork it and try for a resolution.

any suggestions welcome :)

regards,
Jon

**Comment by cyan-confluent** [comment] 2017-11-06 23:52
@joncourt I think the problem you are describing is a different problem than the original poster for this ticket (which is caused by hostname mismatches, and is a bigger problem because it affects most deployment models). 

As for your case, I think private IPs technically should still work, but I don't know enough about your VPC setup to know where the problem lies or whether your hypothesis is accurate.

Because your issue may be different, I'm inclined to close this issue, would you open up another one describing your setup?

Also, were you able to test this recently (within the hour? The master template just recently got updated from the PR).

**Comment by dbtucker** [comment] 2017-11-08 16:54
Looks like the initial problem was related to the behavior of "/bin/hostname", and @cyan-confluent 's consistent use of "hostname -s" has resolved them for most deployments.

**Closed by dbtucker** 2017-11-08 16:54 UTC
